configServiceAddress:
  ip: 127.0.0.1
  port: 9001
httpOuterAddress:
  ip: 127.0.0.1
  port: 9004
httpInnerAddress:
  ip: 0.0.0.0
  port: 9004
moduleName: router
instanceUuid: 3f4faf30-8482-48ef-931a-b15575a3af1d
